const azoSansTypography = {
  typography: {
    htmlFontSize: 16,
    fontSize: 14,
    fontFamily: 'AzoSansRegular',
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 300,
      fontSize: '4rem',
      lineHeight: 1.167,
      letterSpacing: '-0.01562em',
    },
    h2: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 300,
      fontSize: '3.2rem',
      lineHeight: 1.2,
      letterSpacing: '-0.00833em',
      //   color: black70,
    },
    h3: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '2.8rem',
      lineHeight: 1.167,
      letterSpacing: '0em',
      // color: black70,
    },
    h4: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '2.125rem',
      lineHeight: 1.235,
      letterSpacing: '0.00735em',
      //   color: black70,
    },
    h5: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '1.5rem',
      lineHeight: 1.334,
      letterSpacing: '0em',
      //   color: black70,
    },
    h6: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 500,
      fontSize: '1.25rem',
      lineHeight: 1.6,
      letterSpacing: '0.0075em',
      //   color: black80,
    },
    subtitle1: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '1rem',
      lineHeight: 1.75,
      letterSpacing: '0.00938em',
      //   color: black30,
    },
    subtitle2: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 500,
      fontSize: '0.875rem',
      lineHeight: 1.57,
      letterSpacing: '0.00714em',
      //   color: black30,
    },
    body1: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      //   fontSize: '1rem',
      fontSize: '1.2rem',
      lineHeight: 1.5,
      letterSpacing: '0.00938em',
      //   color: darkBlue70,
    },
    body2: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      //   fontSize: '0.875rem',
      fontSize: '1rem',
      lineHeight: 1.43,
      letterSpacing: '0.01071em',
      //   color: darkBlue70,
    },
    button: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 500,
      //   fontSize: '0.875rem',
      fontSize: '1rem',
      lineHeight: 1.75,
      letterSpacing: '0.02857em',
      textTransform: 'uppercase',
    },
    caption: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '0.75rem',
      lineHeight: 1.66,
      letterSpacing: '0.03333em',
      //   color: black30,
    },
    overline: {
      fontFamily: 'AzoSansRegular',
      fontWeight: 400,
      fontSize: '0.75rem',
      lineHeight: 2.66,
      letterSpacing: '0.08333em',
      textTransform: 'uppercase',
    },
  },
};

export default azoSansTypography;
