const PROPERTY_LEASE_DETAILS_EDITABLE_DISPLAY_CONF = [
  {
    type: 'String',
    key: 'id',
    label: 'ID',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'Money',
    key: 'rent',
    label: 'Rent',
    fieldProps: {},
  },
  {
    type: 'DateTime',
    key: 'createdAt',
    label: 'Created At',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'DateTime',
    key: 'updatedAt',
    label: 'Updated At',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'String',
    key: 'bankRef',
    label: 'bankRef',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'SelectOneEnum',
    __type: 'LeaseStage',
    key: 'stage',
    label: 'stage',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'String',
    key: 'placeId',
    label: 'placeId',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'String',
    key: 'location',
    label: 'location',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'String',
    key: 'locationLat',
    label: 'locationLat',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'String',
    key: 'locationLng',
    label: 'locationLng',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'canAcceptPayment',
    label: 'canAcceptPayment',
    fieldProps: {},
  },
  {
    type: 'Int',
    key: 'bathrooms',
    label: 'bathrooms',
    fieldProps: {},
  },
  {
    type: 'Int',
    key: 'garageSpaces',
    label: 'garageSpaces',
    fieldProps: {},
  },
  {
    type: 'Int',
    key: 'offStreetSpaces',
    label: 'offStreetSpaces',
    fieldProps: {},
  },
  {
    type: 'SelectMultipleEnum',
    __type: 'IndoorFeature',
    key: 'indoorFeatures',
    label: 'indoorFeatures',
    fieldProps: {},
  },
  {
    type: 'SelectMultipleEnum',
    __type: 'OutdoorFeature',
    key: 'outdoorFeatures',
    label: 'outdoorFeatures',
    fieldProps: {},
  },
  {
    type: 'SelectOneEnum',
    key: 'bondType',
    __type: 'BondType',
    label: 'Bond Type',
    fieldProps: {},
  },
  {
    type: 'DateTime',
    key: 'moveInDate',
    label: 'moveInDate',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'DateTime',
    key: 'expiryDate',
    label: 'expiryDate',
    editable: false,
    fieldProps: {},
  },
  {
    type: 'SelectOneEnum',
    key: 'tenancyType',
    __type: 'TenancyType',
    label: 'tenancyType',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'petsAllowed',
    label: 'petsAllowed',
    fieldProps: {},
  },
  {
    type: 'SelectMultipleEnum',
    __type: 'Pet',
    key: 'pets',
    label: 'pets',
    fieldProps: {},
  },
  {
    type: 'Int',
    key: 'maximumOccupants',
    label: 'maximumOccupants',
    fieldProps: {},
  },
  {
    type: 'SelectMultipleEnum',
    __type: 'PropertyChattel',
    key: 'chattels',
    label: 'chattels',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'landlordProtectionCover',
    label: 'landlordProtectionCover',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'freeGlassCover',
    label: 'freeGlassCover',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'workingAlarms',
    label: 'workingAlarms',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'inHallway3mOfEachBedroom',
    label: 'inHallway3mOfEachBedroom',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'tenYearPhotoelectricAlarms',
    label: 'tenYearPhotoelectricAlarms',
    fieldProps: {},
  },
  {
    type: 'Boolean',
    key: 'alarmsEachLevel',
    label: 'alarmsEachLevel',
    fieldProps: {},
  },
];
export default PROPERTY_LEASE_DETAILS_EDITABLE_DISPLAY_CONF;
